# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - stg-kentool-customer-portal

on:
  push:
    branches:
      - release/staging
  workflow_dispatch:

env:
  REACT_APP_API_ENDPOINT:  ${{ secrets.STG_REACT_APP_API_ENDPOINT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
        
      - name: 'Deploy to Azure Web App on STAGING environment'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'stg-kentool-customer-portal'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_85A6626203AF430592BD9F199E06BAA5 }}
          package: .
